apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-simple-build-vdgg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-simple-build-vdgg
    app.kubernetes.io/part-of: build-suite-test-application-mwhn
  name: test-simple-build-vdgg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-simple-build-vdgg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-simple-build-vdgg
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-mmdj-tenant/build-suite-test-application-mwhn/test-simple-build-vdgg@sha256:31885177fe6a00b9543c2318c75bd89a930361a206fc9948c3b1f01d6fea6511
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
